# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxUtilityExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxUtilityExample
  pod 'RxCocoa', '~> 4.5'
  pod 'RxSwift', '~> 4.5'
end
